services:
  mongodb:
    image: mongo:7
    container_name: kinhthanh-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: kinhthanh
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
