/**
 * Create full-book YouTube video with subtitles.
 *
 * Title: "Kitô giáo Tỉnh thức: Thế giới – Bản ngã – Từ bi" (Full Audiobook)
 * Format: 1920×1080 MP4, H.264, AAC, subtitles burnt-in
 *
 * Strategy:
 * 1. Use individual chapter MP3 durations to get accurate timing
 * 2. Proportionally distribute subtitle lines within each chapter's time window
 * 3. Generate SRT file
 * 4. ffmpeg: cover image + book-full.mp3 + subtitles → MP4
 *
 * Run: npx tsx seed/youtube-full.ts
 * Prerequisites: ffmpeg, book-full.mp3 already generated by tts-book.ts
 */

import fs from "fs";
import path from "path";
import { execSync, spawnSync } from "child_process";
import mongoose from "mongoose";
import { config } from "dotenv";
config({ path: ".env.local" });

const MONGODB_URI = process.env.MONGODB_URI ?? "mongodb://localhost:27017/kinhthanh";
const AUDIO_DIR = path.resolve(process.cwd(), "audio");
const CHAPTERS_DIR = path.join(AUDIO_DIR, "chapters");
const PARTS_DIR = path.join(AUDIO_DIR, "parts");

const COVER_IMAGE = path.join(AUDIO_DIR, "cover.png");
const FULL_AUDIO = path.join(AUDIO_DIR, "book-full.mp3");
const OUTPUT_SRT = path.join(AUDIO_DIR, "book-full.srt");
const OUTPUT_MP4 = path.join(AUDIO_DIR, "youtube-full.mp4");

// Lines per subtitle card — shorter = more cards = easier to read while listening
const WORDS_PER_CARD = 12;

// Schemas
const EpisodeSchema = new mongoose.Schema({}, { strict: false });
const BookMetaSchema = new mongoose.Schema({}, { strict: false });
const Episode = mongoose.models.Episode ?? mongoose.model("Episode", EpisodeSchema);
const BookMeta = mongoose.models.BookMeta ?? mongoose.model("BookMeta", BookMetaSchema);

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function clean(text: string): string {
  return (text ?? "")
    .replace(/\*\*/g, "").replace(/\*/g, "").replace(/#+\s/g, "")
    .replace(/\s+/g, " ").trim();
}

/** Get MP3 duration in seconds using ffprobe */
function getMp3Duration(filePath: string): number {
  if (!fs.existsSync(filePath)) return 0;
  try {
    const result = spawnSync("ffprobe", [
      "-v", "quiet", "-show_entries", "format=duration",
      "-of", "csv=p=0", filePath,
    ], { encoding: "utf8" });
    return parseFloat(result.stdout.trim()) || 0;
  } catch { return 0; }
}

/** Format seconds to SRT timestamp: HH:MM:SS,mmm */
function toSrtTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  const ms = Math.round((seconds % 1) * 1000);
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")},${String(ms).padStart(3, "0")}`;
}

/** Split text into subtitle cards of ~WORDS_PER_CARD words each */
function splitIntoCards(text: string): string[] {
  const words = text.split(/\s+/).filter(w => w.length > 0);
  const cards: string[] = [];
  for (let i = 0; i < words.length; i += WORDS_PER_CARD) {
    cards.push(words.slice(i, i + WORDS_PER_CARD).join(" "));
  }
  return cards;
}

// ---------------------------------------------------------------------------
// Build chapter spoken text (same as tts-book.ts — must match audio order)
// ---------------------------------------------------------------------------

function buildChapterText(ep: Record<string, any>): string {
  const parts: string[] = [];
  parts.push(`Chương ${ep.episodeNumber}. ${ep.title}.`);
  if (ep.chapterOpening?.trim()) parts.push(clean(ep.chapterOpening));
  if (ep.bibleAnchor?.verses?.length) parts.push(`— ${ep.bibleAnchor.verses.join(", ")} —`);
  if (ep.chapterBody?.trim()) parts.push(clean(ep.chapterBody));
  if (ep.chapterClosing?.trim()) parts.push(clean(ep.chapterClosing));
  return parts.join(" ");
}

// ---------------------------------------------------------------------------
// Build SRT with accurate timing from individual MP3 durations
// ---------------------------------------------------------------------------

interface Section {
  label: string;   // for logging
  text: string;
  audioFile: string;
}

async function buildSRT(sections: Section[]): Promise<string> {
  const srtLines: string[] = [];
  let cardIndex = 1;
  let globalTime = 0;

  for (const section of sections) {
    const duration = getMp3Duration(section.audioFile);
    if (duration === 0) {
      console.log(`  [WARN] No audio for "${section.label}", skipping subtitle`);
      continue;
    }

    const cards = splitIntoCards(section.text);
    if (cards.length === 0) continue;

    const timePerCard = duration / cards.length;

    for (let i = 0; i < cards.length; i++) {
      const start = globalTime + i * timePerCard;
      // End slightly before next card to avoid overlap
      const end = globalTime + (i + 1) * timePerCard - 0.1;

      srtLines.push(String(cardIndex++));
      srtLines.push(`${toSrtTime(start)} --> ${toSrtTime(Math.max(start + 0.5, end)}`);
      srtLines.push(cards[i]);
      srtLines.push("");
    }

    globalTime += duration;
    console.log(`  [SRT] ${section.label} — ${duration.toFixed(1)}s, ${cards.length} cards`);
  }

  return srtLines.join("\n");
}

// ---------------------------------------------------------------------------
// Generate background image with text overlay using ffmpeg (if cover missing)
// ---------------------------------------------------------------------------

function ensureCoverImage(): void {
  if (fs.existsSync(COVER_IMAGE)) return;

  console.log("  [COVER] Generating cover image...");
  // Create a simple dark background with text using ffmpeg
  execSync(
    `ffmpeg -y -f lavfi -i color=c=#1a1a2e:size=1920x1080:rate=1 ` +
    `-vf "drawtext=text='Kitô giáo Tỉnh thức':fontsize=72:fontcolor=white:x=(w-text_w)/2:y=h/2-120," ` +
    `drawtext=text='Thế giới – Bản ngã – Từ bi':fontsize=48:fontcolor=#c5a882:x=(w-text_w)/2:y=h/2-20 ` +
    `-frames:v 1 "${COVER_IMAGE}"`,
    { stdio: "pipe" }
  );
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  // Check prerequisites
  if (!fs.existsSync(FULL_AUDIO)) {
    console.error(`ERROR: ${FULL_AUDIO} not found. Run tts-book.ts first.`);
    process.exit(1);
  }

  ensureCoverImage();

  await mongoose.connect(MONGODB_URI);
  console.log("Connected to MongoDB.\n");

  const metaRecords = await BookMeta.find({}).lean() as any[];
  const meta: Record<string, string> = {};
  for (const r of metaRecords) meta[r.key] = r.content ?? "";

  const episodes = await Episode.find({ status: "published" })
    .sort({ workstream: 1, episodeNumber: 1 })
    .lean() as Record<string, any>[];

  await mongoose.disconnect();

  // Build sections list matching the audio order from tts-book.ts
  const sections: Section[] = [];

  // Intro
  const introFile = path.join(PARTS_DIR, "intro.mp3");
  if (meta["intro"] && fs.existsSync(introFile)) {
    sections.push({
      label: "Lời mở đầu",
      text: `Lời mở đầu. ${clean(meta["intro"])}`,
      audioFile: introFile,
    });
  }

  for (const ws of ["A", "B", "C", "D", "E"]) {
    // Preamble
    const preambleKey = `preamble-${ws}`;
    const preambleFile = path.join(PARTS_DIR, `preamble-${ws.toLowerCase()}.mp3`);
    if (meta[preambleKey] && fs.existsSync(preambleFile)) {
      sections.push({
        label: `Dẫn nhập Phần ${ws}`,
        text: clean(meta[preambleKey]),
        audioFile: preambleFile,
      });
    }

    // Chapters
    for (const ep of episodes.filter(e => e.workstream === ws)) {
      const fileName = `${ep.workstream.toLowerCase()}-${String(ep.episodeNumber).padStart(2, "0")}.mp3`;
      const chapterFile = path.join(CHAPTERS_DIR, fileName);
      sections.push({
        label: `${ep.workstream}${ep.episodeNumber}: ${ep.title}`,
        text: buildChapterText(ep),
        audioFile: chapterFile,
      });
    }
  }

  // Conclusion
  const conclusionFile = path.join(PARTS_DIR, "conclusion.mp3");
  if (meta["conclusion"] && fs.existsSync(conclusionFile)) {
    sections.push({
      label: "Kết luận",
      text: `Kết luận. ${clean(meta["conclusion"])}`,
      audioFile: conclusionFile,
    });
  }

  console.log(`Building SRT for ${sections.length} sections...\n`);
  const srt = await buildSRT(sections);
  fs.writeFileSync(OUTPUT_SRT, srt, "utf8");
  const cardCount = (srt.match(/^\d+$/gm) ?? []).length;
  console.log(`\nSRT saved: ${OUTPUT_SRT} (${cardCount} subtitle cards)`);

  // Get total audio duration
  const totalDuration = getMp3Duration(FULL_AUDIO);
  console.log(`Audio duration: ${(totalDuration / 60).toFixed(1)} minutes`);

  // Build MP4
  console.log(`\nRendering MP4...`);
  console.log(`  Input: ${COVER_IMAGE}`);
  console.log(`  Audio: ${FULL_AUDIO}`);
  console.log(`  Subtitles: ${OUTPUT_SRT}`);
  console.log(`  Output: ${OUTPUT_MP4}`);
  console.log(`  (This may take several minutes...)\n`);

  // Escape SRT path for ffmpeg filter
  const srtEscaped = OUTPUT_SRT.replace(/\\/g, "/").replace(/:/g, "\\:");

  execSync(
    `ffmpeg -y ` +
    `-loop 1 -i "${COVER_IMAGE}" ` +
    `-i "${FULL_AUDIO}" ` +
    `-filter_complex ` +
      `"[0:v]scale=1920:1080,format=yuv420p[v]; ` +
      `[v]subtitles='${srtEscaped}':` +
        `force_style='FontName=Arial,FontSize=26,PrimaryColour=&Hffffff,` +
        `OutlineColour=&H80000000,Outline=2,Shadow=1,` +
        `MarginV=80,Alignment=2'[vout]" ` +
    `-map "[vout]" -map 1:a ` +
    `-c:v libx264 -preset medium -crf 20 ` +
    `-c:a aac -b:a 192k ` +
    `-shortest ` +
    `-r 1 ` +
    `"${OUTPUT_MP4}"`,
    { stdio: "inherit", timeout: 3600_000 }
  );

  const sizeMB = (fs.statSync(OUTPUT_MP4).size / 1024 / 1024).toFixed(0);
  console.log(`\n✓ Done! ${OUTPUT_MP4} (${sizeMB} MB)`);
  console.log(`  Duration: ~${(totalDuration / 60).toFixed(0)} minutes`);
  console.log(`\nYouTube title: Kitô giáo Tỉnh thức: Thế giới – Bản ngã – Từ bi | Full Audiobook`);
  console.log(`YouTube description: 39 chapters, 5 parts, voice: Charon`);
}

main().catch(e => { console.error("Fatal:", e); process.exit(1); });
